s/­//g
s/\.//g
s/+//g
s/Baden-Württemberg/BW/g
s/Bayern/BY/g
s/Berlin/BE/g
s/Brandenburg/BB/g
s/Bremen/HB/g
s/Hamburg/HH/g
s/Hessen/HE/g
s/Mecklenburg-Vorpommern/MV/g
s/Niedersachsen/NI/g
s/Nordrhein-Westfalen/NW/g
s/Rheinland-Pfalz/RP/g
s/Saarland/SL/g
s/Sachsen\-Anhalt/ST/g
s/Sachsen/SN/g
s/Schleswig-Holstein/SH/g
s/Thüringen/TH/g
s/Gesamt/DE/g
